name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and test
      run: |
        # Build Docker image
        docker build -t simple-go-app:latest .
        
        # Test the image
        docker run -d --name test-app -p 8080:8080 simple-go-app:latest
        sleep 5
        
        # Test health endpoint
        curl -f http://localhost:8080/health || exit 1
        
        # Test metrics endpoint  
        curl -f http://localhost:8080/metrics || exit 1
                
        docker stop test-app
        echo "Build and tests passed"
    
    - name: Build and push to GitHub Registry
      run: |
        # Login to GitHub Container Registry
        echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
        # Build and tag image
        docker build -t ghcr.io/chembartsev/simple-go-app:latest .
        
        # Push to GitHub Registry
        docker push ghcr.io/chembartsev/simple-go-app:latest
        
        echo "pushed to GitHub Registry"
    
    - name: Deploy instructions
      run: |
        echo "CI/CD Pipeline completed successfully!"
        echo ""
        echo "Deploy on VM:"
        echo "cd ~/simple-go-app"
        echo "echo '${{ secrets.GHCR_TOKEN }}' | docker login ghcr.io -u ${{ github.actor }} --password-stdin"
        echo "docker-compose pull app"
        echo "docker-compose up -d"
        echo ""
        echo "Check deployment:"
        echo "docker-compose ps"
        echo "curl http://localhost/health"
        echo ""
        echo "Access your application:"
        echo "App: http://localhost"
        echo "Grafana: http://localhost:3000 (admin/admin123)"
        echo "Prometheus: http://localhost:9090"
        echo ""
        echo "Image available at: ghcr.io/chembartsev/simple-go-app:latest" 
