name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and test
      run: |
        # Build Docker image
        docker build -t simple-go-app:latest .
        
        # Test the image
        docker run -d --name test-app -p 8080:8080 simple-go-app:latest
        sleep 5
        
        # Test health endpoint
        curl -f http://localhost:8080/health || exit 1
        
        # Test metrics endpoint  
        curl -f http://localhost:8080/metrics || exit 1
        
        docker stop test-app
        echo "✅ Build and test passed"
    
    - name: Deploy instructions
      run: |
        echo "To deploy manually:"
        echo "1. git pull"
        echo "2. docker-compose down"
        echo "3. docker-compose up -d --build"
        echo ""
        echo "Access:"
        echo "App: http://your-server"
        echo "Grafana: http://your-server:3000"
        echo "Prometheus: http://your-server:9090"
